### ISSUE TITLE
Stuck on password loading on MacOS

### ISSUE THREAD

**Issue by gabe-santos** [alangrainger/epic-journal#1]
I successfully installed electron w/ Epic Journal but when I went in to create a new journal and it asked me for a password I put a random one in and now I'm stuck on password loading

**Comment by alangrainger** [comment]
Before you put the password in, can you click the View menu, and then Developer Tools. It should open a right sidebar. 

Then put your password in and let me know what message comes up in the box on the right. Thanks.

**Comment by alangrainger** [comment]
Try also using a blank password and let me know if that works.

**Comment by GrapeSodas** [comment]
Sorry forgot to mention I'm on MacOS. I followed your directions on changing the code and I think I did everything right. Here's what I got when I entered with a blank password:

![screen shot 2017-12-07 at 10 01 39 pm](https://user-images.githubusercontent.com/34319104/33753067-3d5ef208-db9a-11e7-9bd8-e09886bb6d6b.jpg)

And then when I try entering the password I assume I set, nothing shows up in the console and it just gives me a loading screen.

**Comment by GrapeSodas** [comment]
Just noticed these pop up on my terminal every time I try entering a password

![screen shot 2017-12-07 at 10 06 08 pm](https://user-images.githubusercontent.com/34319104/33753192-e11ce0bc-db9a-11e7-8fbb-2089cc94ce4c.jpg)

**Comment by alangrainger** [comment]
Unfortunately that is expected behaviour on MacOS. I am unable to get https://github.com/fritx/unix-sqlcipher/ to work correctly.

I have opened an issue with the dev, but so far it's not resolved.

If you are a Mac developer, please see if you can do any better! My thread is here: https://github.com/fritx/unix-sqlcipher/issues/4

Thanks :)

**Comment by alangrainger** [comment]
Will be fixed in v2 with "@journeyapps/sqlcipher"
