### ISSUE TITLE
Cannot install on win10

### ISSUE THREAD

**Issue by ronzhin-dmitry** [alangrainger/epic-journal#4]
Hello!

I try yarn install on my win10 system, but it gives errors. Here is the log:

 sqlite3@3.1.4 preinstall C:\Users\Dmitry\Downloads\epic-journal-master\epic-journal-master\node_modules\win-sqlcipher\node_modules\sqlite3
 npm install node-pre-gyp

npm WARN deprecated boom@2.10.1: This version is no longer maintained. Please upgrade to the latest version.
npm WARN deprecated cryptiles@2.0.5: This version is no longer maintained. Please upgrade to the latest version.
npm WARN deprecated hoek@2.16.3: This version is no longer maintained. Please upgrade to the latest version.
npm notice created a lockfile as package-lock.json. You should commit this file.
+ node-pre-gyp@0.6.39
added 114 packages from 78 contributors and audited 268 packages in 7.878s
found 8 moderate severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details

sqlite3@3.1.4 install C:\Users\Dmitry\Downloads\epic-journal-master\epic-journal-master\node_modules\win-sqlcipher\node_modules\sqlite3
 node-pre-gyp install --fallback-to-build

gyp ERR! configure error
gyp ERR! stack Error: Command failed: C:\Users\Dmitry\Anaconda3\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:294:12)
gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:970:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--module=C:\\Users\\Dmitry\\Downloads\\epic-journal-master\\epic-journal-master\\node_modules\\win-sqlcipher\\node_modules\\sqlite3\\lib\\binding\\node-v64-win32-x64\\node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=C:\\Users\\Dmitry\\Downloads\\epic-journal-master\\epic-journal-master\\node_modules\\win-sqlcipher\\node_modules\\sqlite3\\lib\\binding\\node-v64-win32-x64"
gyp ERR! cwd C:\Users\Dmitry\Downloads\epic-journal-master\epic-journal-master\node_modules\win-sqlcipher\node_modules\sqlite3
gyp ERR! node -v v10.15.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=C:\Users\Dmitry\Downloads\epic-journal-master\epic-journal-master\node_modules\win-sqlcipher\node_modules\sqlite3\lib\binding\node-v64-win32-x64\node_sqlite3.node --module_name=node_sqlite3 --module_path=C:\Users\Dmitry\Downloads\epic-journal-master\epic-journal-master\node_modules\win-sqlcipher\node_modules\sqlite3\lib\binding\node-v64-win32-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\Dmitry\Downloads\epic-journal-master\epic-journal-master\node_modules\win-sqlcipher\node_modules\sqlite3\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:970:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
node-pre-gyp ERR! System Windows_NT 10.0.17134
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Dmitry\\Downloads\\epic-journal-master\\epic-journal-master\\node_modules\\win-sqlcipher\\node_modules\\sqlite3\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\Users\Dmitry\Downloads\epic-journal-master\epic-journal-master\node_modules\win-sqlcipher\node_modules\sqlite3
node-pre-gyp ERR! node -v v10.15.1
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
node-pre-gyp ERR! not ok
Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=C:\Users\Dmitry\Downloads\epic-journal-master\epic-journal-master\node_modules\win-sqlcipher\node_modules\sqlite3\lib\binding\node-v64-win32-x64\node_sqlite3.node --module_name=node_sqlite3 --module_path=C:\Users\Dmitry\Downloads\epic-journal-master\epic-journal-master\node_modules\win-sqlcipher\node_modules\sqlite3\lib\binding\node-v64-win32-x64' (1)
npm WARN epic-journal@1.0.7 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sqlite3@3.1.4 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sqlite3@3.1.4 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Dmitry\AppData\Roaming\npm-cache\_logs\2019-02-23T06_04_47_816Z-debug.log

C:\Users\Dmitry\Downloads\epic-journal-master\epic-journal-master>yarn install
yarn install v1.13.0
info No lockfile found.
[1/4] Resolving packages...
warning win-sqlcipher > sqlite3 > node-pre-gyp > hawk > hoek@2.16.3: This version is no longer maintained. Please upgrade to the latest version.
warning win-sqlcipher > sqlite3 > node-pre-gyp > hawk > boom@2.10.1: This version is no longer maintained. Please upgrade to the latest version.
warning win-sqlcipher > sqlite3 > node-pre-gyp > hawk > boom > hoek@2.16.3: This version is no longer maintained. Please upgrade to the latest version.
warning win-sqlcipher > sqlite3 > node-pre-gyp > hawk > cryptiles@2.0.5: This version is no longer maintained. Please upgrade to the latest version.
warning win-sqlcipher > sqlite3 > node-pre-gyp > hawk > cryptiles > boom@2.10.1: This version is no longer maintained. Please upgrade to the latest version.
warning win-sqlcipher > sqlite3 > node-pre-gyp > hawk > sntp > hoek@2.16.3: This version is no longer maintained. Please upgrade to the latest version.
warning babili-webpack-plugin > babel-preset-babili@0.1.4: babili has been renamed to babel-minify. Please update to babel-preset-minify
warning css-loader > cssnano > postcss-merge-rules > browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
warning css-loader > cssnano > autoprefixer > browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
warning css-loader > cssnano > postcss-merge-rules > caniuse-api > browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
warning electron > electron-download > nugget > progress-stream > through2 > xtend > object-keys@0.4.0:
warning eslint > file-entry-cache > flat-cache > circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.
[2/4] Fetching packages...
info fsevents@1.2.7: The platform "win32" is incompatible with this module.
info "fsevents@1.2.7" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
[1/4] ⠁ sqlite3
[-/4] ⠁ waiting...
[-/4] ⠁ waiting...
error C:\Users\Dmitry\Downloads\epic-journal-master\epic-journal-master\node_modules\sqlite3: Command failed.
Exit code: 1
Command: node-pre-gyp install --fallback-to-build
Arguments:
Directory: C:\Users\Dmitry\Downloads\epic-journal-master\epic-journal-master\node_modules\sqlite3
Output:
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.6.39
node-pre-gyp info using node@10.15.1 | win32 | x64
node-pre-gyp info check checked for "C:\Users\Dmitry\Downloads\epic-journal-master\epic-journal-master\node_modules\sqlite3\lib\binding\node-v64-win32-x64\node_sqlite3.node" (not found)
node-pre-gyp http GET https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.4/node-v64-win32-x64.tar.gz
node-pre-gyp http 403 https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.4/node-v64-win32-x64.tar.gz
node-pre-gyp ERR! Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.4/node-v64-win32-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for sqlite3@3.1.4 and node@10.15.1 (node-v64 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp http 403 status code downloading tarball https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.4/node-v64-win32-x64.tar.gz
node-pre-gyp ERR! Tried to download(undefined): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.4/node-v64-win32-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for sqlite3@3.1.4 and node@10.15.1 (node-v64 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp http Connection closed while downloading tarball file

C:\Users\Dmitry\Downloads\epic-journal-master\epic-journal-master\node_modules\sqlite3>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" clean )  else (node "" clean )

C:\Users\Dmitry\Downloads\epic-journal-master\epic-journal-master\node_modules\sqlite3>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" clean )  else (node "" clean )
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@10.15.1 | win32 | x64
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@10.15.1 | win32 | x64
gyp info ok
gyp info ok

C:\Users\Dmitry\Downloads\epic-journal-master\epic-journal-master\node_modules\sqlite3>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" configure --fallback-to-build --module=C:\Users\Dmitry\Downloads\epic-journal-master\epic-journal-master\node_modules\sqlite3\lib\binding\node-v64-win32-x64\node_sqlite3.node --module_name=node_sqlite3 --module_path=C:\Users\Dmitry\Downloads\epic-journal-master\epic-journal-master\node_modules\sqlite3\lib\binding\node-v64-win32-x64 )  else (node "" configure --fallback-to-build --module=C:\Users\Dmitry\Downloads\epic-journal-master\epic-journal-master\node_modules\sqlite3\lib\binding\node-v64-win32-x64\node_sqlite3.node --module_name=node_sqlite3 --module_path=C:\Users\Dmitry\Downloads\epic-journal-master\epic-journal-master\node_modules\sqlite3\lib\binding\node-v64-win32-x64 )

C:\Users\Dmitry\Downloads\epic-journal-master\epic-journal-master\node_modules\sqlite3>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" configure --fallback-to-build --module=C:\Users\Dmitry\Downloads\epic-journal-master\epic-journal-master\node_modules\sqlite3\lib\binding\node-v64-win32-x64\node_sqlite3.node --module_name=node_sqlite3 --module_path=C:\Users\Dmitry\Downloads\epic-journal-master\epic-journal-master\node_modules\sqlite3\lib\binding\node-v64-win32-x64 )  else (node "" configure --fallback-to-build --module=C:\Users\Dmitry\Downloads\epic-journal-master\epic-journal-master\node_modules\sqlite3\lib\binding\node-v64-win32-x64\node_sqlite3.node --module_name=node_sqlite3 --module_path=C:\Users\Dmitry\Downloads\epic-journal-master\epic-journal-master\node_modules\sqlite3\lib\binding\node-v64-win32-x64 )
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@10.15.1 | win32 | x64
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@10.15.1 | win32 | x64
gyp ERR! configure error
gyp ERR! stack Error: Command failed: C:\Users\Dmitry\Anaconda3\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:294:12)
gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:970:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--module=C:\\Users\\Dmitry\\Downloads\\epic-journal-master\\epic-journal-master\\node_modules\\sqlite3\\lib\\binding\\node-v64-win32-x64\\node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=C:\\Users\\Dmitry\\Downloads\\epic-journal-master\\epic-journal-master\\node_modules\\sqlite3\\lib\\binding\\node-v64-win32-x64"
gyp ERR! cwd C:\Users\Dmitry\Downloads\epic-journal-master\epic-journal-master\node_modules\sqlite3
gyp ERR! node -v v10.15.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp.cmd configure --fallback-to-build --module=C:\Users\Dmitry\Downloads\epic-journal-master\epic-journal-master\node_modules\sqlite3\lib\binding\node-v64-win32-x64\node_sqlite3.node --module_name=node_sqlite3 --module_path=C:\Users\Dmitry\Downloads\epic-journal-master\epic-journal-master\node_modules\sqlite3\lib\binding\node-v64-win32-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\Dmitry\Downloads\epic-journal-master\epic-journal-master\node_modules\sqlite3\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:970:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
node-pre-gyp ERR! System Windows_NT 10.0.17134
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Dmitry\\Downloads\\epic-journal-master\\epic-journal-master\\node_modules\\sqlite3\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\Users\Dmitry\Downloads\epic-journal-master\epic-journal-master\node_modules\sqlite3
node-pre-gyp ERR! node -v v10.15.1
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
node-pre-gyp ERR! not ok
Failed to execute 'node-gyp.cmd configure --fallback-to-build --module=C:\Users\Dmitry\Downloads\epic-journal-master\epic-journal-master\node_modules\sqlite3\lib\binding\node-v64-win32-x64\node_sqlite3.node --module_name=node_sqlite3 --module_path=C:\Users\Dmitry\Downloads\epic-journal-master\epic-journal-master\node_modules\sqlite3\lib\binding\node-v64-win32-x64' (1)
gyp ERR! configure error
gyp ERR! stack Error: Command failed: C:\Users\Dmitry\Anaconda3\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:294:12)
gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:970:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--module=C:\\Users\\Dmitry\\Downloads\\epic-journal-master\\epic-journal-master\\node_modules\\sqlite3\\lib\\binding\\node-v64-win32-x64\\node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=C:\\Users\\Dmitry\\Downloads\\epic-journal-master\\epic-journal-master\\node_modules\\sqlite3\\lib\\binding\\node-v64-win32-x64"
gyp ERR! cwd C:\Users\Dmitry\Downloads\epic-journal-master\epic-journal-master\node_modules\sqlite3
gyp ERR! node -v v10.15.1
`

It seems to be some kind of error with SQLite, I tried to install it via npm and didn't succeed either.

**Comment by alangrainger** [comment]
Yeah - SQLite (specifically the winsqlcipher build) was a huge pain to get working.

I've now been slowly updating the code to us @journeyapps/sqlcipher, which actually builds properly.

No ETA for when I'll have it up and running unfortunately. The Windows release still functions fine and I still use it every day, but I do plan to get the modernised version up at some point.

**Comment by ronzhin-dmitry** [comment]
> Yeah - SQLite (specifically the winsqlcipher build) was a huge pain to get working.
> 
> I've now been slowly updating the code to us @journeyapps/sqlcipher, which actually builds properly.
> 
> No ETA for when I'll have it up and running unfortunately. The Windows release still functions fine and I still use it every day, but I do plan to get the modernised version up at some point.

Unfortunately no progress, tried out everything, just can't get it running. Will search for something else

**Comment by alangrainger** [comment]
@ronzhin-dmitry - no, what I mean is the pre-compiled .exe release stil works fine.

You shouldn't need to build it yourself.

**Comment by ronzhin-dmitry** [comment]
> @ronzhin-dmitry - no, what I mean is the pre-compiled .exe release stil works fine.
> 
> You shouldn't need to build it yourself.

Sorry for stupid question then: where can I find it? =) I tried to compile the project since didn't find a pre-compiled one.

**Comment by ronzhin-dmitry** [comment]
> On the releases page - right here :)
> 
> https://github.com/alangrainger/epic-journal/releases/tag/v.1.0.7

OMG, I'm an idiot. Thank you so much!
