### ISSUE TITLE
Exporting

### ISSUE THREAD

**Issue by Spidersouris** [alangrainger/epic-journal#5]
I can't seem to export nor decrypt my journal. Could you please create a tutorial on how to do so?

**Comment by alangrainger** [comment]
Hi Enzo

You can open up the file from SQLiteBrowser, and you'll have all the data
right there unencrypted:

https://sqlitebrowser.org/dl/

**Comment by Spidersouris** [comment]
Thanks! I was using the classic version instead of SQLCipher, which is why it wouldn't work, lol. Thanks again.
