### ISSUE TITLE
can not change file path

### ISSUE THREAD

**Issue by RealIvyWong** [alangrainger/epic-journal#7]
Hey! Thank you for your beautiful software.

I found a bug in recent days. If I cut the .epic file to other paths, the journal contents I wrote before will disappear and a same blank file will be created in original path.

**Comment by alangrainger** [comment]
Hi @RealIvyWong 

That should be no issue - you just need to go File > Open, and then select the new location that you moved your file to :)

Let me know how that goes.

**Comment by RealIvyWong** [comment]
It works! Thank you!
