### ISSUE TITLE
Sign the application

### ISSUE THREAD

**Issue by Aaron-Junker** [alangrainger/epic-journal#9]
Sign the application so it can be installed without the windows protect your pc prompt

**Comment by alangrainger** [comment]
@Aaron-Junker are you happy to pay for the code-signing certificate? I can send you my Paypal if you like.

**Comment by alangrainger** [comment]
@Aaron-Junker are you happy to pay for the code-signing certificate? 

The DigiCert one is only $500 per year, so if you'd like to go with that one I can send you my Paypal and I can get it signed fairly quick :)

**Comment by Aaron-Junker** [comment]
Oh i didnt know its so expensive. I'm sorry.

**Comment by Shihabus-Sakib-Rad** [comment]
I came to know about this software from your [Reddit](https://www.reddit.com/r/software/comments/7b5m5l/i_need_a_crossplatform_journaldiary_program/) post. But I couldn't find the link to android app?
Also, regrading Smartscreen blocking, you can submit it [here](https://www.microsoft.com/en-us/wdsi/filesubmission). Smartscreen will whitelist it in 1 or 2 days. Also, Before that you should use a self signed certificate. {It will build reputation over time}
